# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=80)),
                ('hvp_status', models.CharField(choices=[('Interim', 'Interim')], default='Interim', max_length=32)),
                ('hvp_date', models.DateField()),
                ('background', models.TextField()),
                ('standard_regulation', models.TextField()),
                ('licensing', models.CharField(max_length=200)),
                ('genetics_society', models.CharField(max_length=200)),
                ('genetics_society_url', models.URLField()),
                ('dna_analysis_regulation', models.TextField()),
                ('dna_storage_regulation', models.TextField()),
                ('dna_reporting_regulation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('icon', models.FileField(null=True, upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='external_data',
            field=models.ManyToManyField(to='country.ExternalData'),
        ),
        migrations.AddField(
            model_name='country',
            name='other_societies',
            field=models.ManyToManyField(to='country.Society'),
        ),
        migrations.AddField(
            model_name='country',
            name='personnel',
            field=models.ManyToManyField(related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='projects',
            field=models.ManyToManyField(to='country.Project'),
        ),
        migrations.AddField(
            model_name='country',
            name='representatives',
            field=models.ManyToManyField(related_name='representative', to=settings.AUTH_USER_MODEL),
        ),
    ]
